# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pisiyap.ui'
#
# Created: Thu Jan 27 23:20:29 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Pisiyap(object):
    def setupUi(self, Pisiyap):
        Pisiyap.setObjectName(_fromUtf8("Pisiyap"))
        Pisiyap.resize(682, 320)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pisiyap.sizePolicy().hasHeightForWidth())
        Pisiyap.setSizePolicy(sizePolicy)
        Pisiyap.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pisiyap.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Pisiyap.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Pisiyap)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_21 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.pisiyapTab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pisiyapTab.sizePolicy().hasHeightForWidth())
        self.pisiyapTab.setSizePolicy(sizePolicy)
        self.pisiyapTab.setBaseSize(QtCore.QSize(525, 322))
        self.pisiyapTab.setUsesScrollButtons(False)
        self.pisiyapTab.setObjectName(_fromUtf8("pisiyapTab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_15 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_2.addWidget(self.label_15)
        self.label_10 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(33)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_14 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_2.addWidget(self.label_14)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.brwsBut = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brwsBut.sizePolicy().hasHeightForWidth())
        self.brwsBut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.brwsBut.setFont(font)
        self.brwsBut.setObjectName(_fromUtf8("brwsBut"))
        self.gridLayout_2.addWidget(self.brwsBut, 0, 0, 1, 1)
        self._pkgerName = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._pkgerName.sizePolicy().hasHeightForWidth())
        self._pkgerName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self._pkgerName.setFont(font)
        self._pkgerName.setObjectName(_fromUtf8("_pkgerName"))
        self.gridLayout_2.addWidget(self._pkgerName, 1, 0, 1, 1)
        self._pkgerEmail = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._pkgerEmail.sizePolicy().hasHeightForWidth())
        self._pkgerEmail.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self._pkgerEmail.setFont(font)
        self._pkgerEmail.setObjectName(_fromUtf8("_pkgerEmail"))
        self.gridLayout_2.addWidget(self._pkgerEmail, 2, 0, 1, 1)
        self.brwsLine = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brwsLine.sizePolicy().hasHeightForWidth())
        self.brwsLine.setSizePolicy(sizePolicy)
        self.brwsLine.setObjectName(_fromUtf8("brwsLine"))
        self.gridLayout_2.addWidget(self.brwsLine, 0, 1, 1, 1)
        self.pkgerName = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pkgerName.sizePolicy().hasHeightForWidth())
        self.pkgerName.setSizePolicy(sizePolicy)
        self.pkgerName.setObjectName(_fromUtf8("pkgerName"))
        self.gridLayout_2.addWidget(self.pkgerName, 1, 1, 1, 1)
        self.pkgerEmail = QtGui.QLineEdit(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pkgerEmail.sizePolicy().hasHeightForWidth())
        self.pkgerEmail.setSizePolicy(sizePolicy)
        self.pkgerEmail.setObjectName(_fromUtf8("pkgerEmail"))
        self.gridLayout_2.addWidget(self.pkgerEmail, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cancelBut = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBut.sizePolicy().hasHeightForWidth())
        self.cancelBut.setSizePolicy(sizePolicy)
        self.cancelBut.setMaximumSize(QtCore.QSize(80, 27))
        self.cancelBut.setBaseSize(QtCore.QSize(80, 27))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.cancelBut.setFont(font)
        self.cancelBut.setObjectName(_fromUtf8("cancelBut"))
        self.gridLayout_3.addWidget(self.cancelBut, 0, 1, 1, 1)
        self.creatConfig = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.creatConfig.sizePolicy().hasHeightForWidth())
        self.creatConfig.setSizePolicy(sizePolicy)
        self.creatConfig.setMaximumSize(QtCore.QSize(80, 27))
        self.creatConfig.setBaseSize(QtCore.QSize(80, 27))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.creatConfig.setFont(font)
        self.creatConfig.setObjectName(_fromUtf8("creatConfig"))
        self.gridLayout_3.addWidget(self.creatConfig, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.pisiyapTab.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_31 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(654, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.label_4 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        spacerItem3 = QtGui.QSpacerItem(649, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.brwsBut_ = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brwsBut_.sizePolicy().hasHeightForWidth())
        self.brwsBut_.setSizePolicy(sizePolicy)
        self.brwsBut_.setMinimumSize(QtCore.QSize(120, 27))
        self.brwsBut_.setObjectName(_fromUtf8("brwsBut_"))
        self.horizontalLayout.addWidget(self.brwsBut_)
        self.brwsLine_ = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brwsLine_.sizePolicy().hasHeightForWidth())
        self.brwsLine_.setSizePolicy(sizePolicy)
        self.brwsLine_.setObjectName(_fromUtf8("brwsLine_"))
        self.horizontalLayout.addWidget(self.brwsLine_)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_31.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(649, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_30 = QtGui.QGridLayout()
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.copyArchive = QtGui.QCheckBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyArchive.sizePolicy().hasHeightForWidth())
        self.copyArchive.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.copyArchive.setFont(font)
        self.copyArchive.setObjectName(_fromUtf8("copyArchive"))
        self.gridLayout_30.addWidget(self.copyArchive, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem6, 0, 2, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_30, 2, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(651, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem7, 3, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self._archiveAddr = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._archiveAddr.sizePolicy().hasHeightForWidth())
        self._archiveAddr.setSizePolicy(sizePolicy)
        self._archiveAddr.setObjectName(_fromUtf8("_archiveAddr"))
        self.gridLayout_8.addWidget(self._archiveAddr, 1, 0, 1, 1)
        self._pckgVer = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._pckgVer.sizePolicy().hasHeightForWidth())
        self._pckgVer.setSizePolicy(sizePolicy)
        self._pckgVer.setObjectName(_fromUtf8("_pckgVer"))
        self.gridLayout_8.addWidget(self._pckgVer, 2, 0, 1, 1)
        self.homePage = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homePage.sizePolicy().hasHeightForWidth())
        self.homePage.setSizePolicy(sizePolicy)
        self.homePage.setObjectName(_fromUtf8("homePage"))
        self.gridLayout_8.addWidget(self.homePage, 0, 1, 1, 3)
        self.archiveAddr = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.archiveAddr.sizePolicy().hasHeightForWidth())
        self.archiveAddr.setSizePolicy(sizePolicy)
        self.archiveAddr.setObjectName(_fromUtf8("archiveAddr"))
        self.gridLayout_8.addWidget(self.archiveAddr, 1, 1, 1, 3)
        self.pkgVer = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pkgVer.sizePolicy().hasHeightForWidth())
        self.pkgVer.setSizePolicy(sizePolicy)
        self.pkgVer.setReadOnly(True)
        self.pkgVer.setObjectName(_fromUtf8("pkgVer"))
        self.gridLayout_8.addWidget(self.pkgVer, 2, 1, 1, 1)
        self._homePage = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._homePage.sizePolicy().hasHeightForWidth())
        self._homePage.setSizePolicy(sizePolicy)
        self._homePage.setObjectName(_fromUtf8("_homePage"))
        self.gridLayout_8.addWidget(self._homePage, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 2, 2, 1, 1)
        self.newPkgVer = QtGui.QLineEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newPkgVer.sizePolicy().hasHeightForWidth())
        self.newPkgVer.setSizePolicy(sizePolicy)
        self.newPkgVer.setObjectName(_fromUtf8("newPkgVer"))
        self.gridLayout_8.addWidget(self.newPkgVer, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.gridLayout_33 = QtGui.QGridLayout()
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.backBut = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBut.sizePolicy().hasHeightForWidth())
        self.backBut.setSizePolicy(sizePolicy)
        self.backBut.setMaximumSize(QtCore.QSize(80, 27))
        self.backBut.setObjectName(_fromUtf8("backBut"))
        self.gridLayout_33.addWidget(self.backBut, 0, 1, 1, 1)
        self.nextBut = QtGui.QPushButton(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextBut.sizePolicy().hasHeightForWidth())
        self.nextBut.setSizePolicy(sizePolicy)
        self.nextBut.setMaximumSize(QtCore.QSize(80, 27))
        self.nextBut.setCheckable(False)
        self.nextBut.setObjectName(_fromUtf8("nextBut"))
        self.gridLayout_33.addWidget(self.nextBut, 0, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_33.addItem(spacerItem8, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_33)
        self.gridLayout_31.addLayout(self.verticalLayout, 4, 0, 1, 1)
        self.pisiyapTab.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self._pkgName = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._pkgName.sizePolicy().hasHeightForWidth())
        self._pkgName.setSizePolicy(sizePolicy)
        self._pkgName.setMinimumSize(QtCore.QSize(143, 19))
        self._pkgName.setObjectName(_fromUtf8("_pkgName"))
        self.gridLayout_6.addWidget(self._pkgName, 0, 0, 1, 1)
        self.pkgName = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pkgName.sizePolicy().hasHeightForWidth())
        self.pkgName.setSizePolicy(sizePolicy)
        self.pkgName.setReadOnly(True)
        self.pkgName.setObjectName(_fromUtf8("pkgName"))
        self.gridLayout_6.addWidget(self.pkgName, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.label_9 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self._newPkgName = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._newPkgName.sizePolicy().hasHeightForWidth())
        self._newPkgName.setSizePolicy(sizePolicy)
        self._newPkgName.setMinimumSize(QtCore.QSize(143, 19))
        self._newPkgName.setObjectName(_fromUtf8("_newPkgName"))
        self.gridLayout_7.addWidget(self._newPkgName, 0, 0, 1, 1)
        self._pkgerName_2 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._pkgerName_2.sizePolicy().hasHeightForWidth())
        self._pkgerName_2.setSizePolicy(sizePolicy)
        self._pkgerName_2.setMinimumSize(QtCore.QSize(143, 19))
        self._pkgerName_2.setObjectName(_fromUtf8("_pkgerName_2"))
        self.gridLayout_7.addWidget(self._pkgerName_2, 1, 0, 1, 1)
        self._pkgerEmail_2 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._pkgerEmail_2.sizePolicy().hasHeightForWidth())
        self._pkgerEmail_2.setSizePolicy(sizePolicy)
        self._pkgerEmail_2.setMinimumSize(QtCore.QSize(143, 19))
        self._pkgerEmail_2.setObjectName(_fromUtf8("_pkgerEmail_2"))
        self.gridLayout_7.addWidget(self._pkgerEmail_2, 2, 0, 1, 1)
        self.newPkgName = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newPkgName.sizePolicy().hasHeightForWidth())
        self.newPkgName.setSizePolicy(sizePolicy)
        self.newPkgName.setObjectName(_fromUtf8("newPkgName"))
        self.gridLayout_7.addWidget(self.newPkgName, 0, 1, 1, 1)
        self.pkgerName_ = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pkgerName_.sizePolicy().hasHeightForWidth())
        self.pkgerName_.setSizePolicy(sizePolicy)
        self.pkgerName_.setObjectName(_fromUtf8("pkgerName_"))
        self.gridLayout_7.addWidget(self.pkgerName_, 1, 1, 1, 1)
        self.pkgerEmail_ = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pkgerEmail_.sizePolicy().hasHeightForWidth())
        self.pkgerEmail_.setSizePolicy(sizePolicy)
        self.pkgerEmail_.setObjectName(_fromUtf8("pkgerEmail_"))
        self.gridLayout_7.addWidget(self.pkgerEmail_, 2, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem12, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_7)
        self.gridLayout_15.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.backBut_1 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBut_1.sizePolicy().hasHeightForWidth())
        self.backBut_1.setSizePolicy(sizePolicy)
        self.backBut_1.setMaximumSize(QtCore.QSize(80, 27))
        self.backBut_1.setObjectName(_fromUtf8("backBut_1"))
        self.gridLayout_14.addWidget(self.backBut_1, 0, 1, 1, 1)
        self.nextBut_1 = QtGui.QPushButton(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextBut_1.sizePolicy().hasHeightForWidth())
        self.nextBut_1.setSizePolicy(sizePolicy)
        self.nextBut_1.setMaximumSize(QtCore.QSize(80, 27))
        self.nextBut_1.setObjectName(_fromUtf8("nextBut_1"))
        self.gridLayout_14.addWidget(self.nextBut_1, 0, 2, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem13, 0, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 1, 0, 1, 1)
        self.pisiyapTab.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_17 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem14, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self._license_2 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._license_2.sizePolicy().hasHeightForWidth())
        self._license_2.setSizePolicy(sizePolicy)
        self._license_2.setMinimumSize(QtCore.QSize(91, 22))
        self._license_2.setObjectName(_fromUtf8("_license_2"))
        self.gridLayout_11.addWidget(self._license_2, 1, 0, 1, 1)
        self._isA_2 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._isA_2.sizePolicy().hasHeightForWidth())
        self._isA_2.setSizePolicy(sizePolicy)
        self._isA_2.setMinimumSize(QtCore.QSize(91, 22))
        self._isA_2.setObjectName(_fromUtf8("_isA_2"))
        self.gridLayout_11.addWidget(self._isA_2, 2, 0, 1, 1)
        self.license = QtGui.QComboBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(211)
        sizePolicy.setVerticalStretch(22)
        sizePolicy.setHeightForWidth(self.license.sizePolicy().hasHeightForWidth())
        self.license.setSizePolicy(sizePolicy)
        self.license.setObjectName(_fromUtf8("license"))
        self.license.addItem(_fromUtf8(""))
        self.license.setItemText(0, _fromUtf8(""))
        self.license.addItem(_fromUtf8(""))
        self.license.addItem(_fromUtf8(""))
        self.license.addItem(_fromUtf8(""))
        self.license.addItem(_fromUtf8(""))
        self.license.addItem(_fromUtf8(""))
        self.license.addItem(_fromUtf8(""))
        self.license.addItem(_fromUtf8(""))
        self.license.addItem(_fromUtf8(""))
        self.license.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.license, 1, 1, 1, 1)
        self.isA = QtGui.QComboBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(211)
        sizePolicy.setVerticalStretch(22)
        sizePolicy.setHeightForWidth(self.isA.sizePolicy().hasHeightForWidth())
        self.isA.setSizePolicy(sizePolicy)
        self.isA.setObjectName(_fromUtf8("isA"))
        self.isA.addItem(_fromUtf8(""))
        self.isA.setItemText(0, _fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.isA.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.isA, 2, 1, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem15, 2, 2, 1, 1)
        self._license_3 = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(81)
        sizePolicy.setVerticalStretch(72)
        sizePolicy.setHeightForWidth(self._license_3.sizePolicy().hasHeightForWidth())
        self._license_3.setSizePolicy(sizePolicy)
        self._license_3.setMinimumSize(QtCore.QSize(81, 22))
        self._license_3.setObjectName(_fromUtf8("_license_3"))
        self.gridLayout_11.addWidget(self._license_3, 1, 2, 1, 1)
        self.newLicense = QtGui.QLineEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newLicense.sizePolicy().hasHeightForWidth())
        self.newLicense.setSizePolicy(sizePolicy)
        self.newLicense.setObjectName(_fromUtf8("newLicense"))
        self.gridLayout_11.addWidget(self.newLicense, 1, 3, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem16, 2, 3, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_11, 1, 0, 1, 1)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self._summary = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._summary.sizePolicy().hasHeightForWidth())
        self._summary.setSizePolicy(sizePolicy)
        self._summary.setMinimumSize(QtCore.QSize(91, 22))
        self._summary.setObjectName(_fromUtf8("_summary"))
        self.gridLayout_12.addWidget(self._summary, 0, 0, 1, 1)
        self._description = QtGui.QLabel(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._description.sizePolicy().hasHeightForWidth())
        self._description.setSizePolicy(sizePolicy)
        self._description.setMinimumSize(QtCore.QSize(91, 22))
        self._description.setObjectName(_fromUtf8("_description"))
        self.gridLayout_12.addWidget(self._description, 1, 0, 1, 1)
        self.summary = QtGui.QPlainTextEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(255)
        sizePolicy.setVerticalStretch(51)
        sizePolicy.setHeightForWidth(self.summary.sizePolicy().hasHeightForWidth())
        self.summary.setSizePolicy(sizePolicy)
        self.summary.setMinimumSize(QtCore.QSize(414, 51))
        self.summary.setObjectName(_fromUtf8("summary"))
        self.gridLayout_12.addWidget(self.summary, 0, 1, 1, 1)
        self.description = QtGui.QPlainTextEdit(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(211)
        sizePolicy.setVerticalStretch(81)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setMinimumSize(QtCore.QSize(414, 81))
        self.description.setObjectName(_fromUtf8("description"))
        self.gridLayout_12.addWidget(self.description, 1, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_12, 2, 0, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.backBut_2 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBut_2.sizePolicy().hasHeightForWidth())
        self.backBut_2.setSizePolicy(sizePolicy)
        self.backBut_2.setMaximumSize(QtCore.QSize(80, 27))
        self.backBut_2.setObjectName(_fromUtf8("backBut_2"))
        self.gridLayout_13.addWidget(self.backBut_2, 0, 1, 1, 1)
        self.nextBut_2 = QtGui.QPushButton(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextBut_2.sizePolicy().hasHeightForWidth())
        self.nextBut_2.setSizePolicy(sizePolicy)
        self.nextBut_2.setMaximumSize(QtCore.QSize(80, 27))
        self.nextBut_2.setObjectName(_fromUtf8("nextBut_2"))
        self.gridLayout_13.addWidget(self.nextBut_2, 0, 2, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem17, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_13, 3, 0, 1, 1)
        self.pisiyapTab.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_19 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem18, 0, 0, 1, 1)
        self.gridLayout_18 = QtGui.QGridLayout()
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_3 = QtGui.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_18.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 1, 0, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem19, 2, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.autoTools = QtGui.QRadioButton(self.tab_5)
        self.autoTools.setChecked(True)
        self.autoTools.setObjectName(_fromUtf8("autoTools"))
        self.gridLayout_9.addWidget(self.autoTools, 0, 1, 1, 1)
        self.qt4Tools = QtGui.QRadioButton(self.tab_5)
        self.qt4Tools.setObjectName(_fromUtf8("qt4Tools"))
        self.gridLayout_9.addWidget(self.qt4Tools, 2, 1, 1, 1)
        self.cmakeTools = QtGui.QRadioButton(self.tab_5)
        self.cmakeTools.setObjectName(_fromUtf8("cmakeTools"))
        self.gridLayout_9.addWidget(self.cmakeTools, 0, 3, 1, 1)
        self.kde4Tools = QtGui.QRadioButton(self.tab_5)
        self.kde4Tools.setObjectName(_fromUtf8("kde4Tools"))
        self.gridLayout_9.addWidget(self.kde4Tools, 0, 5, 1, 1)
        self.pyTools = QtGui.QRadioButton(self.tab_5)
        self.pyTools.setObjectName(_fromUtf8("pyTools"))
        self.gridLayout_9.addWidget(self.pyTools, 2, 3, 1, 1)
        self.sconsTools = QtGui.QRadioButton(self.tab_5)
        self.sconsTools.setObjectName(_fromUtf8("sconsTools"))
        self.gridLayout_9.addWidget(self.sconsTools, 2, 5, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem20, 1, 3, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem21, 0, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem22, 0, 6, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem23, 0, 2, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem24, 0, 4, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_9, 3, 0, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem25, 4, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.backBut_3 = QtGui.QPushButton(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBut_3.sizePolicy().hasHeightForWidth())
        self.backBut_3.setSizePolicy(sizePolicy)
        self.backBut_3.setMaximumSize(QtCore.QSize(80, 27))
        self.backBut_3.setObjectName(_fromUtf8("backBut_3"))
        self.gridLayout_10.addWidget(self.backBut_3, 0, 2, 1, 1)
        self.nextBut_3 = QtGui.QPushButton(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextBut_3.sizePolicy().hasHeightForWidth())
        self.nextBut_3.setSizePolicy(sizePolicy)
        self.nextBut_3.setMaximumSize(QtCore.QSize(80, 27))
        self.nextBut_3.setObjectName(_fromUtf8("nextBut_3"))
        self.gridLayout_10.addWidget(self.nextBut_3, 0, 3, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem26, 0, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_10, 5, 0, 1, 1)
        self.pisiyapTab.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem27, 2, 0, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem28, 0, 0, 1, 1)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem29, 4, 0, 1, 1)
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        spacerItem30 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem30, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_22.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_22.addWidget(self.label_5, 2, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_22, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.desktopFile = QtGui.QCheckBox(self.tab_6)
        self.desktopFile.setChecked(False)
        self.desktopFile.setObjectName(_fromUtf8("desktopFile"))
        self.gridLayout.addWidget(self.desktopFile, 0, 1, 1, 1)
        self.serviceScript = QtGui.QCheckBox(self.tab_6)
        self.serviceScript.setObjectName(_fromUtf8("serviceScript"))
        self.gridLayout.addWidget(self.serviceScript, 0, 3, 1, 1)
        self.iconTag = QtGui.QCheckBox(self.tab_6)
        self.iconTag.setObjectName(_fromUtf8("iconTag"))
        self.gridLayout.addWidget(self.iconTag, 2, 1, 1, 1)
        self.comarScript = QtGui.QCheckBox(self.tab_6)
        self.comarScript.setObjectName(_fromUtf8("comarScript"))
        self.gridLayout.addWidget(self.comarScript, 2, 3, 1, 1)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem31, 0, 0, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem32, 0, 4, 1, 1)
        spacerItem33 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem33, 0, 2, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem34, 1, 2, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.backBut_4 = QtGui.QPushButton(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBut_4.sizePolicy().hasHeightForWidth())
        self.backBut_4.setSizePolicy(sizePolicy)
        self.backBut_4.setMaximumSize(QtCore.QSize(80, 27))
        self.backBut_4.setObjectName(_fromUtf8("backBut_4"))
        self.gridLayout_20.addWidget(self.backBut_4, 0, 2, 1, 1)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem35, 0, 1, 1, 1)
        self.nextBut_4 = QtGui.QPushButton(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextBut_4.sizePolicy().hasHeightForWidth())
        self.nextBut_4.setSizePolicy(sizePolicy)
        self.nextBut_4.setMaximumSize(QtCore.QSize(80, 27))
        self.nextBut_4.setObjectName(_fromUtf8("nextBut_4"))
        self.gridLayout_20.addWidget(self.nextBut_4, 0, 3, 1, 1)
        self.openDirectory = QtGui.QCheckBox(self.tab_6)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.openDirectory.setFont(font)
        self.openDirectory.setChecked(True)
        self.openDirectory.setObjectName(_fromUtf8("openDirectory"))
        self.gridLayout_20.addWidget(self.openDirectory, 0, 0, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_20, 5, 0, 1, 1)
        self.pisiyapTab.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_27 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.gridLayout_26 = QtGui.QGridLayout()
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        spacerItem36 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem36, 0, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_26.addWidget(self.label_16, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_26.addWidget(self.label_17, 0, 3, 1, 1)
        spacerItem37 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem37, 0, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(33)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_26.addWidget(self.label_11, 0, 2, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_26, 0, 0, 1, 1)
        self.textBrowser = QtGui.QTextBrowser(self.tab_7)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_27.addWidget(self.textBrowser, 1, 0, 1, 1)
        self.pisiyapTab.addTab(self.tab_7, _fromUtf8(""))
        self.gridLayout_21.addWidget(self.pisiyapTab, 0, 0, 1, 1)
        Pisiyap.setCentralWidget(self.centralwidget)

        self.retranslateUi(Pisiyap)
        self.pisiyapTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.brwsBut, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.selectDir)
        QtCore.QObject.connect(self.brwsBut_, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.brwSource)
        QtCore.QObject.connect(self.cancelBut, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.close)
        QtCore.QObject.connect(self.creatConfig, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.createConfig)
        QtCore.QObject.connect(self.nextBut, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.nextAction)
        QtCore.QObject.connect(self.backBut, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.backAction)
        QtCore.QObject.connect(self.backBut_1, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.backAction)
        QtCore.QObject.connect(self.backBut_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.backAction)
        QtCore.QObject.connect(self.nextBut_1, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.nextAction)
        QtCore.QObject.connect(self.nextBut_2, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.nextAction)
        QtCore.QObject.connect(self.backBut_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.backAction)
        QtCore.QObject.connect(self.nextBut_3, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.nextAction)
        QtCore.QObject.connect(self.backBut_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.backAction)
        QtCore.QObject.connect(self.nextBut_4, QtCore.SIGNAL(_fromUtf8("clicked()")), Pisiyap.createFiles)
        QtCore.QObject.connect(self.copyArchive, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), Pisiyap.copyArchive)
        QtCore.QObject.connect(self.brwsLine_, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Pisiyap.packageName)
        QtCore.QObject.connect(self.desktopFile, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), Pisiyap.checkIconTag)
        QtCore.QObject.connect(self.isA, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Pisiyap.checkDesktopFile)
        QtCore.QMetaObject.connectSlotsByName(Pisiyap)
        Pisiyap.setTabOrder(self.textBrowser, self.brwsBut)
        Pisiyap.setTabOrder(self.brwsBut, self.brwsLine)
        Pisiyap.setTabOrder(self.brwsLine, self.pkgerName)
        Pisiyap.setTabOrder(self.pkgerName, self.pkgerEmail)
        Pisiyap.setTabOrder(self.pkgerEmail, self.cancelBut)
        Pisiyap.setTabOrder(self.cancelBut, self.creatConfig)
        Pisiyap.setTabOrder(self.creatConfig, self.brwsBut_)
        Pisiyap.setTabOrder(self.brwsBut_, self.brwsLine_)
        Pisiyap.setTabOrder(self.brwsLine_, self.copyArchive)
        Pisiyap.setTabOrder(self.copyArchive, self.homePage)
        Pisiyap.setTabOrder(self.homePage, self.archiveAddr)
        Pisiyap.setTabOrder(self.archiveAddr, self.pkgVer)
        Pisiyap.setTabOrder(self.pkgVer, self.newPkgVer)
        Pisiyap.setTabOrder(self.newPkgVer, self.backBut)
        Pisiyap.setTabOrder(self.backBut, self.nextBut)
        Pisiyap.setTabOrder(self.nextBut, self.pkgName)
        Pisiyap.setTabOrder(self.pkgName, self.newPkgName)
        Pisiyap.setTabOrder(self.newPkgName, self.pkgerName_)
        Pisiyap.setTabOrder(self.pkgerName_, self.pkgerEmail_)
        Pisiyap.setTabOrder(self.pkgerEmail_, self.backBut_1)
        Pisiyap.setTabOrder(self.backBut_1, self.nextBut_1)
        Pisiyap.setTabOrder(self.nextBut_1, self.license)
        Pisiyap.setTabOrder(self.license, self.newLicense)
        Pisiyap.setTabOrder(self.newLicense, self.isA)
        Pisiyap.setTabOrder(self.isA, self.summary)
        Pisiyap.setTabOrder(self.summary, self.description)
        Pisiyap.setTabOrder(self.description, self.backBut_2)
        Pisiyap.setTabOrder(self.backBut_2, self.nextBut_2)
        Pisiyap.setTabOrder(self.nextBut_2, self.autoTools)
        Pisiyap.setTabOrder(self.autoTools, self.cmakeTools)
        Pisiyap.setTabOrder(self.cmakeTools, self.kde4Tools)
        Pisiyap.setTabOrder(self.kde4Tools, self.qt4Tools)
        Pisiyap.setTabOrder(self.qt4Tools, self.pyTools)
        Pisiyap.setTabOrder(self.pyTools, self.sconsTools)
        Pisiyap.setTabOrder(self.sconsTools, self.backBut_3)
        Pisiyap.setTabOrder(self.backBut_3, self.nextBut_3)
        Pisiyap.setTabOrder(self.nextBut_3, self.desktopFile)
        Pisiyap.setTabOrder(self.desktopFile, self.serviceScript)
        Pisiyap.setTabOrder(self.serviceScript, self.iconTag)
        Pisiyap.setTabOrder(self.iconTag, self.comarScript)
        Pisiyap.setTabOrder(self.comarScript, self.openDirectory)
        Pisiyap.setTabOrder(self.openDirectory, self.backBut_4)
        Pisiyap.setTabOrder(self.backBut_4, self.nextBut_4)
        Pisiyap.setTabOrder(self.nextBut_4, self.pisiyapTab)

    def retranslateUi(self, Pisiyap):
        Pisiyap.setWindowTitle(QtGui.QApplication.translate("Pisiyap", "PiSiYap - PiSi Source File Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/pisiyap.svg\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Pisiyap", "PiSiYap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/pisiyap.svg\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Pisiyap", "Select a directory where you would like to store PiSi source files", None, QtGui.QApplication.UnicodeUTF8))
        self.brwsBut.setText(QtGui.QApplication.translate("Pisiyap", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self._pkgerName.setText(QtGui.QApplication.translate("Pisiyap", "Packager Name   ", None, QtGui.QApplication.UnicodeUTF8))
        self._pkgerEmail.setText(QtGui.QApplication.translate("Pisiyap", "Packager E-mail  ", None, QtGui.QApplication.UnicodeUTF8))
        self.brwsLine.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Select a directory where you would </span><span style=\" font-family:\'Sans Serif\';\">like to store PiSi source files</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgerName.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Packager name</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgerEmail.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Packager e-mail</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelBut.setText(QtGui.QApplication.translate("Pisiyap", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.creatConfig.setText(QtGui.QApplication.translate("Pisiyap", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.pisiyapTab.setTabText(self.pisiyapTab.indexOf(self.tab), QtGui.QApplication.translate("Pisiyap", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please, select a source file below which</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">you would like to package:</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.brwsBut_.setText(QtGui.QApplication.translate("Pisiyap", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.brwsLine_.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:10pt;\">Select a source file which you would like to package</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.copyArchive.setText(QtGui.QApplication.translate("Pisiyap", "   Check, if you want to copy the archive file into PiSi archive directory", None, QtGui.QApplication.UnicodeUTF8))
        self._archiveAddr.setText(QtGui.QApplication.translate("Pisiyap", "Archive Address", None, QtGui.QApplication.UnicodeUTF8))
        self._pckgVer.setText(QtGui.QApplication.translate("Pisiyap", "Package Version", None, QtGui.QApplication.UnicodeUTF8))
        self.homePage.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Home page</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.archiveAddr.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Archive address</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgVer.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Automatically generated package version. If the generated version is wrong, please specify the correct one in the next field</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._homePage.setText(QtGui.QApplication.translate("Pisiyap", "Home Page", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">or enter new version here</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.newPkgVer.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">New package version</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.backBut.setText(QtGui.QApplication.translate("Pisiyap", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBut.setText(QtGui.QApplication.translate("Pisiyap", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.pisiyapTab.setTabText(self.pisiyapTab.indexOf(self.tab_2), QtGui.QApplication.translate("Pisiyap", "Archive", None, QtGui.QApplication.UnicodeUTF8))
        self._pkgName.setText(QtGui.QApplication.translate("Pisiyap", "Package Name    ", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgName.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Automatically generated package name. If the generated name is wrong, please specify the correct one in the field below</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Pisiyap", "If you would like to change the package name,\n"
"please define it below:", None, QtGui.QApplication.UnicodeUTF8))
        self._newPkgName.setText(QtGui.QApplication.translate("Pisiyap", "New Package Name", None, QtGui.QApplication.UnicodeUTF8))
        self._pkgerName_2.setText(QtGui.QApplication.translate("Pisiyap", "Packager Name   ", None, QtGui.QApplication.UnicodeUTF8))
        self._pkgerEmail_2.setText(QtGui.QApplication.translate("Pisiyap", "Packager E-mail  ", None, QtGui.QApplication.UnicodeUTF8))
        self.newPkgName.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">New package name</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgerName_.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Packager name</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgerEmail_.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Packager e-mail</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.backBut_1.setText(QtGui.QApplication.translate("Pisiyap", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBut_1.setText(QtGui.QApplication.translate("Pisiyap", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.pisiyapTab.setTabText(self.pisiyapTab.indexOf(self.tab_3), QtGui.QApplication.translate("Pisiyap", "Package", None, QtGui.QApplication.UnicodeUTF8))
        self._license_2.setText(QtGui.QApplication.translate("Pisiyap", "License", None, QtGui.QApplication.UnicodeUTF8))
        self._isA_2.setText(QtGui.QApplication.translate("Pisiyap", "IsA", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">If the license is not in this list, please write new license in the next field</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setItemText(1, QtGui.QApplication.translate("Pisiyap", "GPLv1", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setItemText(2, QtGui.QApplication.translate("Pisiyap", "GPLv2", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setItemText(3, QtGui.QApplication.translate("Pisiyap", "GPLv3", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setItemText(4, QtGui.QApplication.translate("Pisiyap", "LGPLv2", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setItemText(5, QtGui.QApplication.translate("Pisiyap", "LGPLv2.1", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setItemText(6, QtGui.QApplication.translate("Pisiyap", "LGPLv3", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setItemText(7, QtGui.QApplication.translate("Pisiyap", "BSD", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setItemText(8, QtGui.QApplication.translate("Pisiyap", "MIT", None, QtGui.QApplication.UnicodeUTF8))
        self.license.setItemText(9, QtGui.QApplication.translate("Pisiyap", "as-is", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">isA tag</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(1, QtGui.QApplication.translate("Pisiyap", "app", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(2, QtGui.QApplication.translate("Pisiyap", "app:console", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(3, QtGui.QApplication.translate("Pisiyap", "app:gui", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(4, QtGui.QApplication.translate("Pisiyap", "app:web", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(5, QtGui.QApplication.translate("Pisiyap", "data", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(6, QtGui.QApplication.translate("Pisiyap", "data:doc", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(7, QtGui.QApplication.translate("Pisiyap", "data:font", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(8, QtGui.QApplication.translate("Pisiyap", "driver", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(9, QtGui.QApplication.translate("Pisiyap", "library", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(10, QtGui.QApplication.translate("Pisiyap", "locale", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(11, QtGui.QApplication.translate("Pisiyap", "kernel", None, QtGui.QApplication.UnicodeUTF8))
        self.isA.setItemText(12, QtGui.QApplication.translate("Pisiyap", "service", None, QtGui.QApplication.UnicodeUTF8))
        self._license_3.setText(QtGui.QApplication.translate("Pisiyap", "New License", None, QtGui.QApplication.UnicodeUTF8))
        self.newLicense.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">New license</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._summary.setText(QtGui.QApplication.translate("Pisiyap", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self._description.setText(QtGui.QApplication.translate("Pisiyap", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.summary.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Short summary of the package. Please, do not use &quot;package name&quot; and do not put a dot signal (.) at the end of a sentence in summary tag</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.description.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Long description of the package. You should specify more detailed information about the package in this tag.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.backBut_2.setText(QtGui.QApplication.translate("Pisiyap", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBut_2.setText(QtGui.QApplication.translate("Pisiyap", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.pisiyapTab.setTabText(self.pisiyapTab.indexOf(self.tab_4), QtGui.QApplication.translate("Pisiyap", "pspec.xml", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Pisiyap", "Please, select the module\n"
"you would like to use in actions.py", None, QtGui.QApplication.UnicodeUTF8))
        self.autoTools.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Select this option if the package is built with autotools</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.autoTools.setText(QtGui.QApplication.translate("Pisiyap", "Auto Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.qt4Tools.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Select this option if the package is built with qt4 tools</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.qt4Tools.setText(QtGui.QApplication.translate("Pisiyap", "Qt4 Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.cmakeTools.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Select this option if the package is built with cmake tools</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cmakeTools.setText(QtGui.QApplication.translate("Pisiyap", "CMake Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.kde4Tools.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Select this option if the package is built with kde4 tools</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.kde4Tools.setText(QtGui.QApplication.translate("Pisiyap", "KDE4 Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.pyTools.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Select this option if the package is built with python tools</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pyTools.setText(QtGui.QApplication.translate("Pisiyap", "Python Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.sconsTools.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Select this option if the package is built with scons tools</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.sconsTools.setText(QtGui.QApplication.translate("Pisiyap", "SCons Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.backBut_3.setText(QtGui.QApplication.translate("Pisiyap", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBut_3.setText(QtGui.QApplication.translate("Pisiyap", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.pisiyapTab.setTabText(self.pisiyapTab.indexOf(self.tab_5), QtGui.QApplication.translate("Pisiyap", "actions.py", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Pisiyap", "pspec.xml and actions.py files will be created automatically.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Pisiyap", "Click extra files you would like to be created:", None, QtGui.QApplication.UnicodeUTF8))
        self.desktopFile.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">With this option selected, you can create desktop file easily. If you select this option, Icon Tag will also be created automatically</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.desktopFile.setText(QtGui.QApplication.translate("Pisiyap", "Create a Desktop file", None, QtGui.QApplication.UnicodeUTF8))
        self.serviceScript.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">If your package has a service daemon, select this option to create service script file automatically</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.serviceScript.setText(QtGui.QApplication.translate("Pisiyap", "Create a Service Script file", None, QtGui.QApplication.UnicodeUTF8))
        self.iconTag.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">Selecting this option will create Icon tag in pspec.xml file in order to show the package icon next to the name of the package in package-manager</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.iconTag.setText(QtGui.QApplication.translate("Pisiyap", "Add an Icon tag", None, QtGui.QApplication.UnicodeUTF8))
        self.comarScript.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt;\">If you need to call some system commands before or after installing the package, use this comar script file template to define these commands</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.comarScript.setText(QtGui.QApplication.translate("Pisiyap", "Create a Comar Script file", None, QtGui.QApplication.UnicodeUTF8))
        self.backBut_4.setText(QtGui.QApplication.translate("Pisiyap", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBut_4.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">When all the fields are filled in, you can create the necessary files by pressing this button</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBut_4.setText(QtGui.QApplication.translate("Pisiyap", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.openDirectory.setToolTip(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt; font-weight:400;\">Opens the directory which contains pisi source files generated by this program</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.openDirectory.setText(QtGui.QApplication.translate("Pisiyap", "Open files directory after creation?", None, QtGui.QApplication.UnicodeUTF8))
        self.pisiyapTab.setTabText(self.pisiyapTab.indexOf(self.tab_6), QtGui.QApplication.translate("Pisiyap", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/pisiyap.svg\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/pisiyap.svg\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Serif\'; font-size:33pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'pardus\'; font-weight:400;\">PiSiYap</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("Pisiyap", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt; font-weight:600;\">version 0.1</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\'; font-size:10pt; font-weight:600;\">Authors:</span><span style=\" font-family:\'Serif\';\"> Murat Şenel, Anıl Özbek</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\';\">  </span><span style=\" font-family:\'Serif\'; font-size:10pt; font-weight:600;\">Art:</span><span style=\" font-family:\'Serif\';\"> Serdar Soytetir, Murat Şenel, Banu Önal</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Serif\';\">  </span><span style=\" font-family:\'Serif\'; font-size:10pt; font-weight:600;\">Test:</span><span style=\" font-family:\'Serif\';\"> Kenan Pelit, Serdar Soytetir, Mehmet Nur Olcay, H. İbrahim Güngör</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/gplv3.png\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pisiyapTab.setTabText(self.pisiyapTab.indexOf(self.tab_7), QtGui.QApplication.translate("Pisiyap", "About", None, QtGui.QApplication.UnicodeUTF8))

import pisiyapicon_rc
